name: test_env_intake-axds
channels:
  - conda-forge
dependencies:
  - python=3.9
  ############## These will have to be adjusted to your specific project
  - cartopy
  - cf_xarray
  - dask
  - netcdf4
  - numba >= 0.49
  - numpy
  - xarray
  - xgcm == 0.5.1
  - zarr
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
